### PR TITLE
integrate with circleci and add in initial discretionary controls

### PR DESCRIPTION
**Pull request by jenwhy-versent**
add in modifications to initial set of discretionary controls & integrate with circleci

### CODE REVIEW

**Comment by felipe1982** [comment]
I would recommend merging the circleci stuff into master first, then doing `add-baselines` PR to master. @jenwhy-versent

**Comment by jenwhy-versent** [comment]
Sounds good. Happy for that to be the case
________________________________

**Comment by felipe1982** [comment]
good, could you please approve #2

**Comment by jenwhy-versent** [comment]
Closing this PR so we can do one to master

**Pull request closed without merging**
